parameters:
#    pumped_pumped.example.class: Pumped\PumpedBundle\Example

services:
#    pumped_pumped.example:
#        class: %pumped_pumped.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
